# Generated by Django 5.2 on 2025-04-24 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0003_remove_ride_end_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="rides.driver",
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="start_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
